apiVersion: batch/v1
kind: Job
metadata:
  name: fortify-dast-job
spec:
  template:
    spec:
      containers:
        - name: fortify-dast-api-caller
          image: bankierubybank/fortify-dast-api-caller:latest
          command: ["/fortify-dast-api-caller.sh"]
          env:
            - name: DAST_API_HOST
              value: "https://172.16.67.168:5001"
            - name: DAST_USERNAME
              value: "dast-caller"
            - name: DAST_PASSWORD
              value: "DAST@Fortify#2023!"
            - name: DAST_CICD_TOKEN
              value: "425e8e62-8d44-4a5c-8c27-95458a09975c"
            - name: DAST_JOB_NAME
              value: "FROM_ARGOCD"
      restartPolicy: Never
